### ISSUE TITLE
Retryer stops retrying after first retryable exception

### ISSUE THREAD

**Issue by uriahcarpenter** [Netflix/feign#236]
JavaDoc for `feign.Retryer` reads:
> Created for each invocation to {@link Client#execute(Request, feign.Request.Options)}. Implementations may keep state to determine if retry operations should continue or not.

However, in practice, and in inspecting the code, it appears that the Retryer object is never re-created.

For example, in our application it's possible that we attempt to query a invalid host. The first time we have an invalid host the retryer correctly retrys 5 times.

```
[DamV1Api#getAssetWithOptions] ---> GET https://invalidcustomer.yden.us/api/rest/asset/uuid/00000000-0000-0000-0000-000000000000 HTTP/1.1
[DamV1Api#getAssetWithOptions] ---> END HTTP (0-byte body)
[DamV1Api#getAssetWithOptions] <--- ERROR UnknownHostException: invalidcustomer.yden.us (63ms)
[DamV1Api#getAssetWithOptions] ---> RETRYING
[DamV1Api#getAssetWithOptions] ---> GET https://invalidcustomer.yden.us/api/rest/asset/uuid/00000000-0000-0000-0000-000000000000 HTTP/1.1
[DamV1Api#getAssetWithOptions] ---> END HTTP (0-byte body)
[DamV1Api#getAssetWithOptions] <--- ERROR UnknownHostException: invalidcustomer.yden.us (3ms)
[DamV1Api#getAssetWithOptions] ---> RETRYING
[DamV1Api#getAssetWithOptions] ---> GET https://invalidcustomer.yden.us/api/rest/asset/uuid/00000000-0000-0000-0000-000000000000 HTTP/1.1
[DamV1Api#getAssetWithOptions] ---> END HTTP (0-byte body)
[DamV1Api#getAssetWithOptions] <--- ERROR UnknownHostException: invalidcustomer.yden.us (2ms)
[DamV1Api#getAssetWithOptions] ---> RETRYING
[DamV1Api#getAssetWithOptions] ---> GET https://invalidcustomer.yden.us/api/rest/asset/uuid/00000000-0000-0000-0000-000000000000 HTTP/1.1
[DamV1Api#getAssetWithOptions] ---> END HTTP (0-byte body)
[DamV1Api#getAssetWithOptions] <--- ERROR UnknownHostException: invalidcustomer.yden.us (2ms)
[DamV1Api#getAssetWithOptions] ---> RETRYING
[DamV1Api#getAssetWithOptions] ---> GET https://invalidcustomer.yden.us/api/rest/asset/uuid/00000000-0000-0000-0000-000000000000 HTTP/1.1
[DamV1Api#getAssetWithOptions] ---> END HTTP (0-byte body)
[DamV1Api#getAssetWithOptions] <--- ERROR UnknownHostException: invalidcustomer.yden.us (6ms)

< 400
< Content-Type: application/json
{
  "error": true,
  "response_code": 400,
  "error_message": "UnknownHostException: invalidcustomer.yden.us"
}
```

However, all subsequent requests never retry and abort after the first call.

```
[DamV1Api#getAssetWithOptions] ---> GET https://invalidcustomer.yden.us/api/rest/asset/uuid/00000000-0000-0000-0000-000000000000 HTTP/1.1
[DamV1Api#getAssetWithOptions] ---> END HTTP (0-byte body)

< 400
< Content-Type: application/json
{
  "error": true,
  "response_code": 400,
  "error_message": "UnknownHostException: invalidcustomer.yden.us"
}
```

My question would be: is this expected behavior and the JavaDoc on Retryer is outdated; or is this a legitimate regression?

**Comment by adriancole** [comment]
Sounds like a bug. Wanna give a go at fixing it?

**Comment by uriahcarpenter** [comment]
@adriancole Sure. Would `newInstance()` be sufficient for object instantiation?

**Comment by adriancole** [comment]
super big bug, btw. Definitely needs to be fixed.

So, before, SynchronousMethodHandler took a `Provider<Retryer>`. We no longer have `Provider` in the classpath, but we need the same effect. I see basically 2 options, and I'm partial to option 2.

#### make Retryer.Factory and fix Feign.Builder
Fixes the scope problem, but adds a type, but complicates `Feign.Builder`
 * Add `Retryer.Factory#create()` which returns a new instance of Retryer.
 * Deprecate `Feign.Builder#retryer(Retryer)` for `Feign.Builder#retryer(Retryer.Factory)`
  * deprecated one could make an anonymous Retryer.Factory using `newInstance()`
 * Fix SynchronousMethodHandler to do `Retryer retryer = this.retryer.create();` instead of `Retryer retryer = this.retryer;`

#### make Retryer cloneable
Fixes the scope problem, breaks custom retryers (which are incidentally broken anyway), but doesn't break `Feign.Builder`
 * Make Retryer implement Cloneable, update type javadoc substituting `Created` with `Cloned`.
```java
/** Called before each invocation to {@link Client#execute(Request, feign.Request.Options)}.*/
@Override
Retryer clone();
```
 * Add cloneable implementation to Retryer.Default. Ex. `return new Default(period, maxPeriod, maxAttempts);`
 * Fix SynchronousMethodHandler to do `Retryer retryer = this.retryer.clone();` instead of `Retryer retryer = this.retryer;`

**Comment by uriahcarpenter** [comment]
Pull request is #239. I found it difficult to directly inspect the cloned Retryer instances, so I had the test version throw an exception if it was reused. Thanks for the pointers!

I'm contributing this code under the Apache 2.0 License.
