### ISSUE TITLE
Move language level to 1.7

### ISSUE THREAD

**Issue by adriancole** [Netflix/feign#289]
Android supports Java language level 1.7 features, even if we should still enforce use of 1.6 apis via animal-sniffer. This should reduce clutter in declarations.

This implies minSdkVersion 19

See https://github.com/square/wire/pull/370

**Comment by adriancole** [comment]
@danilocgomes mentioned he has some legacy apps they expect to update next year. Let's put a deadline in for this that we stop maintaining JRE 6 language level when JRE 9 is out (~ Sep 2016).

There's not much impact to delaying this to next year, as we can already change the language level of tests. One thing I do want is to not need to maintain 2 versions of feign, and delaying this bump can help with this.

**Comment by danilocgomes** [comment]
@adriancole In fact, I can use the current version (or the latest supported) when to work with legacy code. Feign, how it is today, is enough and helps a lot.

I sent you this message because the project aims build clients and It would created the same restriction for all Feign based clients for the newer versions. And when we create clients we may not always control where it will be used.

As I saw the most of your build.gradle was targeting JRE 1.6, I thought that was an objective.

This question arose because we wish standardize all our clients and use Feign (we loved the experience) and we have many projects ranging from JRE 6 to 8. If Feign was unable to support JRE 6, this would be a problem because we would have two client implementations.

But, as I said, I can use the current version without problems for these cases =)

My clients are happier with Feign.

Thanks for your time.
Congratulations for the great work.
