### ISSUE TITLE
Hystrix RxJava Completable support

### ISSUE THREAD

**Issue by padilo** [Netflix/feign#379]
Currently when I'm doing a HystrixFeign client and I didn't expect a body, I use Observable<Void> but It sends a 'null' event. I would expect just a onComplete event if everything works ok, or onError otherwise.

I think behaivior cannot be changed, because it will break backward compatibility, but there is another recommended way to deal with this?

Maybe a good idea add support to Completable in the future, when someone removes that ugly Experimental annotation :)

**Comment by adriancole** [comment]
we can add support for Completable any time imho. @spencergibb what are your thoughts?

**Comment by spencergibb** [comment]
I don't know much about `Completable`. I just skimmed http://akarnokd.blogspot.com/2015/12/the-new-completable-api-part-1.html and http://akarnokd.blogspot.com/2015/12/the-new-completable-api-part-2-final.html

Since our integration is through Hystrix, which doesn't support this as a first class citizen, if the return type is `Completable` we could do something like:
```
toObservable().operator.toCompletable()
```
