### ISSUE TITLE
Question: multiple decoders

### ISSUE THREAD

**Issue by WeipingGuo** [Netflix/feign#406]
I am using feign to call a legacy web service. Unfortunately some api return Json response, some return xml, and others even return plain/text or raw byte array. My current solution is to define three interfaces, each corresponding one response type. Any better way to do it?

Thank you very much
Weiping

**Comment by spencergibb** [comment]
We do something similar using Spring's `HttpMessageConverters` in [`SpringDecoder`](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/support/SpringDecoder.java). Since decoder's have access to the response, you can switch on content-type.

**Comment by WeipingGuo** [comment]
@spencergibb thanks a lot. I am using vanilla Feign, will switch to spring-cloud-netflix. Thanks
